[package]
name = "blueshift-native-escrow"
version = "0.1.0"
edition = "2021"

[features]
default = ["perf"]
perf = []

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = "0.8.4"
pinocchio-associated-token-account = "0.1.1"
pinocchio-system = "0.2.3"
pinocchio-token = "0.3.0"

